// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAli4dKobYS0umSPGFGEcvsIWyHGPc94Dc',
    appId: '1:267071370142:web:4523a258da71cd7cd55c8f',
    messagingSenderId: '267071370142',
    projectId: 'project-3-hamad',
    authDomain: 'project-3-hamad.firebaseapp.com',
    storageBucket: 'project-3-hamad.appspot.com',
    measurementId: 'G-24W5RYBELK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUqGtv-2Y93a-OIJiqvrccPZk6ABHnsk',
    appId: '1:267071370142:android:30e018009f9d55fed55c8f',
    messagingSenderId: '267071370142',
    projectId: 'project-3-hamad',
    storageBucket: 'project-3-hamad.appspot.com',
  );
}
